/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as IdentitiesIndexRouteImport } from './routes/Identities/index'
import { Route as HomeIndexRouteImport } from './routes/Home/index'
import { Route as HabitsIndexRouteImport } from './routes/Habits/index'
import { Route as ElementsIndexRouteImport } from './routes/Elements/index'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const IdentitiesIndexRoute = IdentitiesIndexRouteImport.update({
  id: '/Identities/',
  path: '/Identities/',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeIndexRoute = HomeIndexRouteImport.update({
  id: '/Home/',
  path: '/Home/',
  getParentRoute: () => rootRouteImport,
} as any)
const HabitsIndexRoute = HabitsIndexRouteImport.update({
  id: '/Habits/',
  path: '/Habits/',
  getParentRoute: () => rootRouteImport,
} as any)
const ElementsIndexRoute = ElementsIndexRouteImport.update({
  id: '/Elements/',
  path: '/Elements/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/Elements/': typeof ElementsIndexRoute
  '/Habits/': typeof HabitsIndexRoute
  '/Home/': typeof HomeIndexRoute
  '/Identities/': typeof IdentitiesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/Elements': typeof ElementsIndexRoute
  '/Habits': typeof HabitsIndexRoute
  '/Home': typeof HomeIndexRoute
  '/Identities': typeof IdentitiesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/Elements/': typeof ElementsIndexRoute
  '/Habits/': typeof HabitsIndexRoute
  '/Home/': typeof HomeIndexRoute
  '/Identities/': typeof IdentitiesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/register'
    | '/Elements/'
    | '/Habits/'
    | '/Home/'
    | '/Identities/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/register'
    | '/Elements'
    | '/Habits'
    | '/Home'
    | '/Identities'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/register'
    | '/Elements/'
    | '/Habits/'
    | '/Home/'
    | '/Identities/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  ElementsIndexRoute: typeof ElementsIndexRoute
  HabitsIndexRoute: typeof HabitsIndexRoute
  HomeIndexRoute: typeof HomeIndexRoute
  IdentitiesIndexRoute: typeof IdentitiesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Identities/': {
      id: '/Identities/'
      path: '/Identities'
      fullPath: '/Identities/'
      preLoaderRoute: typeof IdentitiesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Home/': {
      id: '/Home/'
      path: '/Home'
      fullPath: '/Home/'
      preLoaderRoute: typeof HomeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Habits/': {
      id: '/Habits/'
      path: '/Habits'
      fullPath: '/Habits/'
      preLoaderRoute: typeof HabitsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Elements/': {
      id: '/Elements/'
      path: '/Elements'
      fullPath: '/Elements/'
      preLoaderRoute: typeof ElementsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  ElementsIndexRoute: ElementsIndexRoute,
  HabitsIndexRoute: HabitsIndexRoute,
  HomeIndexRoute: HomeIndexRoute,
  IdentitiesIndexRoute: IdentitiesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
