/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as IdentitiesIndexRouteImport } from './routes/Identities/index'
import { Route as HomeIndexRouteImport } from './routes/Home/index'
import { Route as HabitsIndexRouteImport } from './routes/Habits/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const IdentitiesIndexRoute = IdentitiesIndexRouteImport.update({
  id: '/Identities/',
  path: '/Identities/',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeIndexRoute = HomeIndexRouteImport.update({
  id: '/Home/',
  path: '/Home/',
  getParentRoute: () => rootRouteImport,
} as any)
const HabitsIndexRoute = HabitsIndexRouteImport.update({
  id: '/Habits/',
  path: '/Habits/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/Habits/': typeof HabitsIndexRoute
  '/Home/': typeof HomeIndexRoute
  '/Identities/': typeof IdentitiesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/Habits': typeof HabitsIndexRoute
  '/Home': typeof HomeIndexRoute
  '/Identities': typeof IdentitiesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/Habits/': typeof HabitsIndexRoute
  '/Home/': typeof HomeIndexRoute
  '/Identities/': typeof IdentitiesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/Habits/' | '/Home/' | '/Identities/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/Habits' | '/Home' | '/Identities'
  id: '__root__' | '/' | '/Habits/' | '/Home/' | '/Identities/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HabitsIndexRoute: typeof HabitsIndexRoute
  HomeIndexRoute: typeof HomeIndexRoute
  IdentitiesIndexRoute: typeof IdentitiesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Identities/': {
      id: '/Identities/'
      path: '/Identities'
      fullPath: '/Identities/'
      preLoaderRoute: typeof IdentitiesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Home/': {
      id: '/Home/'
      path: '/Home'
      fullPath: '/Home/'
      preLoaderRoute: typeof HomeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Habits/': {
      id: '/Habits/'
      path: '/Habits'
      fullPath: '/Habits/'
      preLoaderRoute: typeof HabitsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HabitsIndexRoute: HabitsIndexRoute,
  HomeIndexRoute: HomeIndexRoute,
  IdentitiesIndexRoute: IdentitiesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
